#
# Makefile for the IHIDDEN hidden curve remover.
#

include ../makeflag.unx

OBJS =	ihidden.o$(IRIT_OBJ_PF) \
	rsi.o$(IRIT_OBJ_PF) \
	cci.o$(IRIT_OBJ_PF)

all:	ihidden$(IRIT_EXE_PF)

ihidden$(IRIT_EXE_PF):	$(OBJS)
	$(CC) $(CFLAGS) -o ihidden$(IRIT_EXE_PF) $(OBJS) $(MOREOBJS) \
	$(IRIT_LIBS) $(IRIT_MORE_LIBS) $(GRAPOGLLIBS) -lm

install: ihidden$(IRIT_EXE_PF)
	mv -f ihidden$(IRIT_EXE_PF) $(IRIT_BIN_DIR)
	cp ihidden.cfg $(IRIT_BIN_DIR)


# DO NOT DELETE THIS LINE -- make depend depends on it.
