#
# This is the make file for the mdl. lib subdirectory.
#
#				Gershon Elber, Aug 1991
#

include ../makeflag.ami

OBJS =  mdl_aux.o mdl_bbox.o mdl_bool.o mdl2bool.o \
	mdl_dbg.o mdl_dum.o \
	mdl_err.o mdl_ftl.o mdl_gen.o \
	mdl_prim.o mdl_ptch.o mdlcnvrt.o

all:	libmdl.a

libmdl.a: $(OBJS)
	rm -f libmdl.a
	ar rcv libmdl.a *.o
	-ranlib libmdl.a

install: libmdl.a
	mv -f libmdl.a $(IRIT_LIB_DIR)

# DO NOT DELETE THIS LINE -- make depend depends on it.
